"""Publish the report as a GitHub issue that is updated in place."""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.parse
import urllib.request

from .report import MARKER

API = "https://api.github.com"
FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n"


def _request(method: str, url: str, token: str, payload: dict | None = None) -> dict | list:
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    if data:
        req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req, timeout=30) as resp:
        body = resp.read().decode("utf-8")
    return json.loads(body) if body else {}


def _find_issue(repo: str, token: str, title: str) -> dict | None:
    query = urllib.parse.urlencode({"state": "open", "per_page": "100"})
    issues = _request("GET", f"{API}/repos/{repo}/issues?{query}", token)
    for issue in issues if isinstance(issues, list) else []:
        if "pull_request" in issue:
            continue
        if issue.get("title") == title or MARKER in (issue.get("body") or ""):
            return issue
    return None


def publish(body: str, title: str, comment_on_change: bool = False) -> str | None:
    """Create or update the tracking issue. Returns its URL, or None if skipped."""
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    repo = os.environ.get("GITHUB_REPOSITORY", "").strip()
    if not token or not repo:
        print("[notify] GITHUB_TOKEN/GITHUB_REPOSITORY unset; skipping issue update")
        return None

    body = body + FOOTER
    try:
        issue = _find_issue(repo, token, title)
        if issue is None:
            created = _request(
                "POST", f"{API}/repos/{repo}/issues", token, {"title": title, "body": body}
            )
            print(f"[notify] opened issue #{created.get('number')}")
            return created.get("html_url")

        number = issue["number"]
        _request("PATCH", f"{API}/repos/{repo}/issues/{number}", token, {"body": body})
        if comment_on_change:
            _request(
                "POST",
                f"{API}/repos/{repo}/issues/{number}/comments",
                token,
                {"body": "New award options found on this run - see the issue body." + FOOTER},
            )
        print(f"[notify] updated issue #{number}")
        return issue.get("html_url")
    except urllib.error.HTTPError as exc:
        print(f"[notify] GitHub API {exc.code}: {exc.read().decode('utf-8','replace')[:300]}")
    except (urllib.error.URLError, TimeoutError) as exc:
        print(f"[notify] GitHub API unreachable: {exc}")
    return None
